import { useEffect, useMemo, useState } from 'react'
import { brand, doctor, featuredServices, navItems, servicePages, stats, testimonials, trustPoints, whyReviva } from './data/siteContent'

const images = {
  hero: 'https://images.unsplash.com/photo-1556228578-8c89e6adf883?auto=format&fit=crop&w=1400&q=85',
  doctor: 'https://images.unsplash.com/photo-1559839734-2b71ea197ec2?auto=format&fit=crop&w=900&q=85',
  skin: 'https://images.unsplash.com/photo-1616394584738-fc6e612e71b9?auto=format&fit=crop&w=900&q=85',
}

export default function App() {
  const [path, setPath] = useState(window.location.pathname)
  const [menuOpen, setMenuOpen] = useState(false)
  const navigate = (href) => { window.history.pushState({}, '', href); setPath(href); setMenuOpen(false); window.scrollTo({ top: 0, behavior: 'smooth' }) }
  useEffect(() => { const fn = () => setPath(window.location.pathname); window.addEventListener('popstate', fn); return () => window.removeEventListener('popstate', fn) }, [])
  const route = useMemo(() => resolveRoute(path), [path])
  return <div className="site"><Header path={path} open={menuOpen} onToggle={() => setMenuOpen(!menuOpen)} navigate={navigate} /><main>{route.type === 'home' ? <Home navigate={navigate} /> : route.type === 'about' ? <About navigate={navigate} /> : route.type === 'services' ? <Services navigate={navigate} /> : route.type === 'service' ? <Service slug={route.slug} navigate={navigate} /> : <NotFound navigate={navigate} />}</main><Footer navigate={navigate} /></div>
}

function resolveRoute(path) { if (path === '/') return { type: 'home' }; if (path === '/about') return { type: 'about' }; if (path === '/services') return { type: 'services' }; const m = path.match(/^\/services\/([^/]+)/); return m ? { type: 'service', slug: m[1] } : { type: 'not-found' } }

function Header({ path, open, onToggle, navigate }) {
  return <><div className="topline">Complimentary consultation available in Noida & Ghaziabad <a href={brand.whatsapp} target="_blank" rel="noreferrer">Book your appointment <span>↗</span></a></div><header className="header"><button className="logo" onClick={() => navigate('/')}><span className="logo-mark">R</span><span><b>REVIVA</b><small>SKIN & SURGERY CLINIC</small></span></button><nav>{navItems.map(item => <button key={item.href} className={path === item.href ? 'active' : ''} onClick={() => navigate(item.href)}>{item.label}{item.children && <small>⌄</small>}</button>)}</nav><div className="header-actions"><a href={`tel:${brand.phoneNoida.replace(/\s/g, '')}`}>Call clinic</a><a className="dark-button" href={brand.whatsapp} target="_blank" rel="noreferrer">Book consultation <span>↗</span></a></div><button className="menu-button" aria-label="Toggle navigation" onClick={onToggle}>{open ? '×' : '☰'}</button></header>{open && <div className="mobile-menu">{navItems.map(item => <button key={item.href} onClick={() => navigate(item.href)}>{item.label}<span>↗</span></button>)}<a href={brand.whatsapp} target="_blank" rel="noreferrer">Book a consultation <span>↗</span></a></div>}</>
}

function Home({ navigate }) {
 return <>
  <section className="hero"><div className="hero-copy"><p className="kicker">DERMATOLOGY · AESTHETICS · WELLNESS</p><h1>Skin care that feels <em>like you.</em></h1><p className="hero-text">Personalised dermatology and aesthetic care, grounded in science and designed for your most confident self.</p><div className="buttons"><a className="dark-button" href={brand.whatsapp} target="_blank" rel="noreferrer">Start your skin journey <span>↗</span></a><button className="text-link" onClick={() => navigate('/services')}>Explore treatments <span>↗</span></button></div><div className="hero-note"><span className="avatars">AT</span><span><b>Trusted by 10,000+ patients</b><small> across Delhi NCR</small></span></div></div><div className="hero-visual"><img src={images.hero} alt="Woman caring for her skin" /><div className="floating-card"><span className="seal">✦</span><p><b>Where integrity</b><br />meets aesthetic.</p></div><div className="image-label">01 <span>Reviva approach</span></div></div></section>
  <section className="marquee"><span>CLINICAL PRECISION</span><i>✦</i><span>NATURAL RESULTS</span><i>✦</i><span>PERSONALISED CARE</span><i>✦</i><span>CLINICAL PRECISION</span></section>
  <section className="section concerns"><div className="section-head"><div><p className="kicker">WHAT BRINGS YOU HERE?</p><h2>Care for every <em>concern.</em></h2></div><p>Whether it&apos;s a small change or a fresh start, we&apos;re here to help you feel at home in your skin.</p></div><div className="concern-grid">{featuredServices.map((s, i) => <button key={s.slug} onClick={() => navigate(`/services/${s.slug}`)} className={`concern concern-${i + 1}`}><span>0{i + 1}</span><h3>{s.title}</h3><p>{s.description}</p><b>Learn more ↗</b></button>)}</div></section>
  <section className="split-section"><div className="split-image"><img src={images.skin} alt="Close-up of healthy skin" /><span>Our philosophy</span></div><div className="split-copy"><p className="kicker">THE REVIVA DIFFERENCE</p><h2>Good skin is a <em>journey,</em> not a trend.</h2><p>At Reviva, we believe the best results are the ones that still look and feel like you. Every plan begins with listening, a thorough assessment, and an honest conversation about what is right for you.</p><div className="proof-row">{stats.slice(0, 3).map(s => <div key={s.label}><strong>{s.value}</strong><span>{s.label}</span></div>)}</div><button className="text-link" onClick={() => navigate('/about')}>Meet Reviva <span>↗</span></button></div></section>
  <section className="section doctor-section"><div className="section-head"><div><p className="kicker">MEET YOUR DERMATOLOGIST</p><h2>Expertise with a <em>human touch.</em></h2></div></div><div className="doctor-card"><div className="doctor-photo"><img src={images.doctor} alt={doctor.name} /><span>Dr. Aarushi Tyagi</span></div><div className="doctor-copy"><p className="quote">“My goal is to make you feel heard, informed, and confident in every step of your care.”</p><p>{doctor.bio}</p><small>{doctor.credentials}</small><button className="text-link" onClick={() => navigate('/about')}>About Dr. Aarushi <span>↗</span></button></div></div></section>
  <section className="testimonial"><p className="kicker">PATIENT STORIES</p><blockquote>“The best investment I made was in feeling comfortable in my own skin.”</blockquote><div className="testimonial-row">{testimonials.map(t => <article key={t.name}><p>“{t.quote}”</p><b>{t.name}</b><small>{t.treatment}</small></article>)}</div></section>
  <CTA />
 </>
}

function About({ navigate }) { return <PageIntro eyebrow="ABOUT REVIVA" title={<>Care that begins with <em>listening.</em></>} description="Reviva Skin & Surgery Clinic brings together clinical dermatology, advanced technology, and a deeply personal approach to care." navigate={navigate}><section className="section about-grid"><div><p className="kicker">OUR PROMISE</p><h2>Science, softened by <em>empathy.</em></h2><p>Founded by {doctor.name}, Reviva is a destination for thoughtful skin, hair, and aesthetic care in Delhi NCR. We never chase trends or promise overnight miracles. We create clear, personalised plans that respect your features, your timeline, and your goals.</p></div><div className="values">{whyReviva.map((x, i) => <div key={x.title}><span>0{i + 1}</span><h3>{x.title}</h3><p>{x.description}</p></div>)}</div></section><CTA /></PageIntro> }
function Services({ navigate }) { return <PageIntro eyebrow="OUR SERVICES" title={<>A considered approach to <em>better skin.</em></>} description="From everyday concerns to advanced aesthetic goals, explore treatments designed around you." navigate={navigate}><section className="section service-list">{servicePages.map((s, i) => <button key={s.slug} onClick={() => navigate(`/services/${s.slug}`)}><span>0{i + 1}</span><div><h3>{s.title}</h3><p>{s.summary}</p></div><b>↗</b></button>)}</section><CTA /></PageIntro> }
function Service({ slug, navigate }) { const service = servicePages.find(s => s.slug === slug); if (!service) return <NotFound navigate={navigate} />; return <PageIntro eyebrow="TREATMENT GUIDE" title={<>{service.title} for <em>your confidence.</em></>} description={service.summary} navigate={navigate}><section className="section service-detail"><div><p className="kicker">DESIGNED AROUND YOU</p><h2>Small steps. <em>Visible change.</em></h2><p>Our team begins with a detailed consultation and recommends only what supports your goals. Treatment plans are tailored to your skin, lifestyle, and comfort.</p><a className="dark-button" href={brand.whatsapp} target="_blank" rel="noreferrer">Book a consultation <span>↗</span></a></div><div><h3>Ideal for</h3>{service.concerns.map(c => <p className="detail-line" key={c}>✦ {c}</p>)}<h3 className="detail-heading">Your Reviva journey</h3><p className="detail-line">Consultation → Assessment → Personalised care → Ongoing support</p></div></section></PageIntro> }
function PageIntro({ eyebrow, title, description, children }) { return <><section className="page-intro"><p className="kicker">{eyebrow}</p><h1>{title}</h1><p>{description}</p></section>{children}</> }
function CTA() { return <section className="cta"><p className="kicker">YOUR SKIN, YOUR STORY</p><h2>Ready to feel good <em>in your skin?</em></h2><p>Begin with a conversation. No pressure, no promises — just thoughtful advice from our team.</p><a className="light-button" href={brand.whatsapp} target="_blank" rel="noreferrer">Book your consultation <span>↗</span></a></section> }
function NotFound({ navigate }) { return <PageIntro eyebrow="404" title={<>Let&apos;s get you <em>home.</em></>} description="The page you are looking for does not exist."><section className="section center"><button className="dark-button" onClick={() => navigate('/')}>Back to homepage <span>↗</span></button></section></PageIntro> }
function Footer({ navigate }) { return <footer><div className="footer-top"><div><button className="logo light-logo" onClick={() => navigate('/')}><span className="logo-mark">R</span><span><b>REVIVA</b><small>SKIN & SURGERY CLINIC</small></span></button><p>Thoughtful dermatology for your most confident self.</p></div><div><p className="footer-label">VISIT US</p><p>Noida · Ghaziabad<br />Delhi NCR, India</p></div><div><p className="footer-label">SAY HELLO</p><a href={`tel:${brand.phoneNoida.replace(/\s/g, '')}`}>{brand.phoneNoida}</a><br /><a href={brand.whatsapp} target="_blank" rel="noreferrer">WhatsApp ↗</a></div></div><div className="footer-bottom"><span>© {new Date().getFullYear()} Reviva Skin & Surgery</span><span>Care, with intention.</span></div></footer> }
